# Local Assessments

```{r}
#| label: gb
#| include: false
# include does not show output or code #| is a special syntax for Quarto 

#When testing and not rendering the report, the if statement returns true but when rendering as the report, the else executes
if (file.exists("pages/Global/gb.R")) {
  source("pages/Global/gb.R")
  source("pages/Data/data.R")
} else {
  source("./Global/gb.R")
  source("./Data/data.R")
}
```

## Preliminary

Quin County Community Health Services is gearing up to start our community health assessment for 2025. As we focus on our internal priorities, we have decided to share the data we've gathered from publicly available sources. This document will be updated with new information as it becomes available throughout the upcoming year.

## Minnesota Student Survey

The Minnesota Student Survey (MSS) is a vital tool for gathering insights into the health, well-being, safety, and academic success of Minnesota's youth. Conducted every three years, this anonymous and confidential survey targets students in grades 5, 8, 9, and 11 across the state. It covers a broad range of topics, including physical activity, nutrition, substance use, mental health, school safety, relationships, sexual activity, and positive behaviors, as well as connections to family, school, and community.

Most school districts in Minnesota participate in the MSS. Although there was a drop in participation statewide in 2022 and some schools or specific grades in Kittson, Marshall, Pennington, Red Lake, and Roseau Counties did not take part in the 2022 survey. We strongly encourage all schools in these counties to join the upcoming 2025 MSS.

The results of the MSS are crucial for incorporating the perspectives of young people into policy-making, program development, and service provision for students. Your participation helps ensure that the voices of our youth are heard and considered in decisions that affect their lives.
